"""phase 3: sale + sale_line + conflict

Revision ID: 088eed0fdb2a
Revises: 777e5d80309e
Create Date: 2026-04-27 01:06:56.713087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088eed0fdb2a'
down_revision: Union[str, None] = '777e5d80309e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_order_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('card_surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('tcgplayer','ebay','shopify_pos')", name='sale_channel_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_order_id')
    )
    op.create_table('conflict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('inventory_unit_id', sa.Integer(), nullable=True),
    sa.Column('external_order_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('oversell','listing_not_found','sync_failed')", name='conflict_kind_check'),
    sa.CheckConstraint("status IN ('open','resolved','ignored')", name='conflict_status_check'),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('inventory_unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('condition_at_sale', sa.String(length=16), nullable=True),
    sa.Column('title_at_sale', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_line')
    op.drop_table('conflict')
    op.drop_table('sale')
    # ### end Alembic commands ###
