"""product: add has_image + number, drop image_url

Revision ID: 6a97164e3d36
Revises: 7c5734b9c212
Create Date: 2026-05-03 19:43:08.245660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a97164e3d36'
down_revision: Union[str, None] = '7c5734b9c212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL on a populated table needs a server_default; existing
    # rows get has_image=False since their JPEG (if any) lives at the
    # legacy ``<id>_in_400x400.jpg`` path which the new naming scheme
    # won't find. Re-fetch will repopulate at the new deterministic
    # location. Plain Python-side default=False is for fresh inserts only.
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'has_image',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )
        batch_op.add_column(sa.Column('number', sa.String(length=32), nullable=True))
        batch_op.drop_column('image_url')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('number')
        batch_op.drop_column('has_image')

    # ### end Alembic commands ###
