"""phase 2: outbound_change queue

Revision ID: 777e5d80309e
Revises: ed607dbc4a97
Create Date: 2026-04-26 22:51:12.054034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777e5d80309e'
down_revision: Union[str, None] = 'ed607dbc4a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('inventory_unit_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('push_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('create','update_qty','update_price','end_listing')", name='outbound_change_action_check'),
    sa.CheckConstraint("channel IN ('tcgplayer','ebay','shopify_pos')", name='outbound_change_channel_check'),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_change', schema=None) as batch_op:
        batch_op.create_index('outbound_change_pending_idx', ['channel', 'enqueued_at'], unique=False, sqlite_where=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_change', schema=None) as batch_op:
        batch_op.drop_index('outbound_change_pending_idx', sqlite_where=None)

    op.drop_table('outbound_change')
    # ### end Alembic commands ###
