"""add product.marketplace_product_id

Revision ID: 7c5734b9c212
Revises: 8c0a4869183b
Create Date: 2026-05-03 19:23:17.568611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5734b9c212'
down_revision: Union[str, None] = '8c0a4869183b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace_product_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_marketplace_product_id'), ['marketplace_product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_marketplace_product_id'))
        batch_op.drop_column('marketplace_product_id')

    # ### end Alembic commands ###
