"""add inventory_unit.reserve_quantity

Revision ID: 8c0a4869183b
Revises: f49aff4cd3a3
Create Date: 2026-05-03 18:12:32.498365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0a4869183b'
down_revision: Union[str, None] = 'f49aff4cd3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL on an existing populated table needs a server-side default;
    # the model's Python-side default=0 only fires for new rows.
    with op.batch_alter_table('inventory_unit', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'reserve_quantity',
                sa.Integer(),
                nullable=False,
                server_default='0',
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_unit', schema=None) as batch_op:
        batch_op.drop_column('reserve_quantity')

    # ### end Alembic commands ###
