"""phase 1: products + inventory_unit + channel_listing + sync_run

Revision ID: ed607dbc4a97
Revises: 0001_initial
Create Date: 2026-04-26 22:30:18.432339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed607dbc4a97'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcgplayer_product_id', sa.Integer(), nullable=True),
    sa.Column('shopify_product_id', sa.Integer(), nullable=True),
    sa.Column('shopify_variant_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('is_foil', sa.Boolean(), nullable=False),
    sa.Column('rarity', sa.String(length=64), nullable=True),
    sa.Column('card_type', sa.String(length=64), nullable=True),
    sa.Column('sealed_subtype', sa.String(length=64), nullable=True),
    sa.Column('supply_category', sa.String(length=64), nullable=True),
    sa.Column('is_online_listable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('single','sealed','supply')", name='product_kind_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopify_product_id'),
    sa.UniqueConstraint('tcgplayer_product_id')
    )
    op.create_table('sync_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_local_edit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'condition', name='inventory_unit_product_condition_uk')
    )
    op.create_table('channel_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_unit_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_listing_id', sa.String(length=64), nullable=True),
    sa.Column('last_pushed_quantity', sa.Integer(), nullable=True),
    sa.Column('last_pushed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_state', sa.String(length=16), nullable=False),
    sa.Column('last_push_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('tcgplayer','ebay','shopify_pos')", name='channel_listing_channel_check'),
    sa.CheckConstraint("sync_state IN ('pending','ok','error')", name='channel_listing_sync_state_check'),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_unit_id', 'channel', name='channel_listing_unit_channel_uk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_listing')
    op.drop_table('inventory_unit')
    op.drop_table('sync_run')
    op.drop_table('product')
    # ### end Alembic commands ###
